######################## default configuration ####################
baseURL = "https://www.simonwei.top"
title = "Simon Wei's blog"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "100"
metaDataFormat = "yaml"
hasCJKLanguage = true
DefaultContentLanguage = "zh"
gcs_engine_id="012737790962522169780:fd1izxsfgrs"
# disable language
disableLanguages = [] # desable language from here
pygmentsUseClasses=true

[outputs]
home = ["HTML", "RSS", "Algolia", "JSON"]
page = ["HTML"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "permalink", "image","description"]
params = ["tags","categories"]

[params.repository]
url = "https://github.com/simonwei97/website"
branch = "main"

[params.search_wowchemy]
min_lenth = 1
threshold = 0.3

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/hightlight/syntax.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/tocbot/tocbot.css"
[[params.plugins.css]]
link = "plugins/bigger-picture/bigger-picture.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/popper/popper.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/hex_md5/hex_md5.js"
[[params.plugins.js]]
link = "plugins/anchor/anchor.min.js"
[[params.plugins.js]]
link = "plugins/tocbot/tocbot.min.js"
[[params.plugins.js]]
link = "plugins/bigger-picture/bigger-picture.min.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "魏晓鹏（Simon Wei）的个人博客"
author = "Simon Wei"
# contact info
address = "Beijing, China"
email = "simonwei@simonwei.top"
wechat = "simonwei97"
# contact form action
contact_form_action = "https://formspree.io/mpzdzdbj" # contact form works with https://formspree.io

# Google Analitycs
google_analitycs_id = "UA-93485976-1" # your id
# Baidu tongji
baidu_key = "11f7d254cfa4e0ca44b175c66d379ecc"
search = true
search_provider = "wowchemy"
enableComment = true
enableAdSense = false
AdSenseClientID = "ca-pub-4029167986768912"
anchored = true # add anchor on each head title in the blog article content
code_copy_button = true
back_to_top_button = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
#[params.subscription]
#enable = true
# mailchimp subsciption
#mailchimp_form_action = "https://xxx.us20.list-manage.com/subscribe/post?u=cca519d8764547a389f52c57f&amp;id=e8e9e07dcc"
# Use RSS instead
#mailchimp_form_name = "b_cca519d8764547a389f52c57f_e8e9e07dcc"

# Ads
[params.ad]
enable= false
image = "images/jksj.jpg"
url = "https://time.geekbang.org/column/intro/100015201?tab=catalog&code=IRLmmVKgTghcFr5iafwl9kZezb48Uhf4Pjdf13-W3ko%3D"
title = "深入剖析 Kubernetes"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social site ########################
# [[params.social]]
# title = "twitter"
# icon = "fa-twitter"
# link = "https://twitter.com/simonwei"

#[[params.social]]
#title = "youtube"
#icon = "fa-youtube"
#link = "https://www.youtube.com/channel/UCwLGlxo3b492bzIgD8lnOKg/"

[[params.social]]
title = "github"
icon = "fa-github"
link = "https://github.com/simonwei97"

[[params.social]]
title = "linkedin"
icon = "fa-linkedin"
link = "https://linkedin.com/in/simonweiio"

[[params.social]]
title = "mail"
icon = "fa-envelope"
link = "mailto:simonwei@simonwei.top"

[[params.social]]
title = "RSS"
icon = "fa-rss"
link = "/blog/index.xml"

################################### English language #####################################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
home = "Home"
# copyright
copyright = "&copy; 2017-2023 Simon Wei All Right Reserved"

# top header
top_header = false
top_header_content = "[Download the eBook: The Current State and Future of the Istio Service Mesh](https://bit.ly/3Vqrlfw)"

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 2

# [[menu.main]]
# name = "Algo"
# URL = "algo"
# weight = 2

[[menu.main]]
name = "Tags"
URL = "tags"
weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5

[[menu.main]]
name = "Universal"
URL = "universal"
weight = 6

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 7


# footer links

[[menu.footer]]
name = "Tetrate Istio Distro"
URL = "https://istio.tetratelabs.io/"

[[menu.footer]]
name = "Cloud Native Community(China)"
URL = "https://cloudnative.to"

[[menu.footer]]
name = "Awesome Cloud Native"
URL = "/awesome-cloud-native/"

#[[menu.footer]]
#name = "Jimmy's YouTube Channel"
#URL = "https://www.youtube.com/channel/UCwLGlxo3b492bzIgD8lnOKg/"


# courses
[[menu.book]]
name = "Envoy Fundamentals"
URL = "https://academy.tetrate.io/courses/envoy-fundamentals"

[[menu.book]]
name = "Istio Fundamentals"
URL = "https://academy.tetrate.io/courses/istio-fundamentals"

################################### Chinese language #####################################
[Languages.zh]
languageName = "中文"
languageCode = "zh"
contentDir = "content/zh"
home = "主页"
title = "Simon Wei"
# copyright
copyright = "&copy; 2017-2023 Simon Wei 保留所有权利"
# top header
top_header = false
top_header_content = "test"

# main menu
[[Languages.zh.menu.main]]
name = "博客"
URL = "blog"
weight = 2

# # main menu
# [[Languages.zh.menu.main]]
# name = "算法"
# URL = "algo"
# weight = 3

[[Languages.zh.menu.main]]
name = "标签"
URL = "tags"
weight = 4

[[Languages.zh.menu.main]]
name = "联系"
URL = "contact"
weight = 5

[[Languages.zh.menu.main]]
name = "常用"
URL = "universal"
weight = 6

[[Languages.zh.menu.main]]
name = "关于"
URL = "about"
weight = 7


# 链接
[[Languages.zh.menu.footer]]
name = "Kubernetes社区"
URL = "https://kubernetes.io/"


# book 教程
[[Languages.zh.menu.book]]
name = "学习 Kubernetes 基础知识"
URL = "https://kubernetes.io/zh-cn/docs/tutorials/kubernetes-basics/"

# friendlink 友链
[[Languages.zh.menu.friendlink]]
name = "Jimmy Song 的博客"
URL = "https://jimmysong.io"

[[Languages.zh.menu.friendlink]]
name = "码农桃花源"
URL = "https://qcrao.com/"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 2
