name: build-and-deploy
on: push
jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
            - name: Setup hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "0.105.0"
                  extended: true
            - name: Build
              run: hugo
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  EXTERNAL_REPOSITORY: simonwei97/simonwei97.github.io
                  PUBLISH_DIR: ./public
                  PUBLISH_BRANCH: main
                  commit_message: ${{ github.event.head_commit.message }}
