name: update-algolia

on:
    schedule:
        - cron: "5 4 * * sun"
jobs:
    build:
        name: Algolia Update
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
            - name: Update Algolia
              run: ./update-algolia.sh
              env:
                  API_KEY: ${{ secrets.API_KEY }}
